# .ffhh:
# network: intern
# .com:
# network: public
#
- title:    Blogs
  text:     lorem ipsum
  icon:     quote-right
  url:      http://wp.ffhh/
  network:  intern
- title:    Radio
  text:     Live Stream von freier Musik
  icon:     file-audio-o
  url:      http://radio.ffhh/
  network:  intern
- title:    Wiki
  text:     lorem ipsum
  icon:     rocket
  url:      https://wiki.freifunk.net/Freifunk_Hamburg
  network:  public
- title:    Verbindung
  text:     Zeige Informationen Ã¼ber den Router mit dem du gerade verbinden bist
  icon:     wifi
  url:      http://knoten.ffhh/
  network:  intern
